config/routes.rb
OnyxProductionManagement::Application.routes.draw do
  resources :bom_materiales

  resources :boms do
    member do
      get "add_materiale_to_bom"
      get "materiales_list"
      get "remove_materiale_from_materiales_list"
    end
    collection do
      get "remove_materiale_from_bom"
    end
  end

  get "import_data/import_data_view" => "import_data#import_data_view"
  post "import_data/upload"
  
  resources :manufactures do
    collection do
      post "search", to: 'manufactures#search_manufactures'
    end
  end

  resources :custom_tables do
    collection do
      get "edit_column"
      post "update_column"
    end
  end

  devise_for :users
  
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
    get    "/users/sign_in" => "devise/sessions#new"
    get    "/users/sign_up" => "devise/registrations#new"
  end
  
  resources :fittings

  resources :packaging_materials

  resources :assembly_boms

  resources :bom_events

  resources :orders

  resources :products do
    member do
      get "boms"
      get "orders"
      get "assembly_boms"
    end
  end

  resources :hardwares

  resources :softwares

  resources :assemblies

  resources :packaging_requirements

  resources :register_orders

  resources :events

  resources :types

  resources :materiales_events

  resources :materiales do    
    collection do
      post "search", to: 'materiales#search_materiales'
      post "update_materiale"
    end
  end

  root 'materiales#index'

  

end

app/models/fitting.rb
class Fitting
  include Mongoid::Document
  field :adapter, type: String
  field :adapter_sticker, type: String
  field :data_line, type: String
  field :headphone, type: String
  field :tf_card, type: String
  field :holster, type: String
  field :remark, type: String
  
  belongs_to :register_order
end

app/controllers/fittings_controller.rb
class FittingsController < ApplicationController
  before_action :set_fitting, only: [:show, :edit, :update, :destroy]

  # GET /fittings
  # GET /fittings.json
  def index
    @fittings = Fitting.all
  end

  # GET /fittings/1
  # GET /fittings/1.json
  def show
  end

  # GET /fittings/new
  def new
    @fitting = Fitting.new
  end

  # GET /fittings/1/edit
  def edit
  end

  # POST /fittings
  # POST /fittings.json
  def create
    @fitting = Fitting.new(fitting_params)

    respond_to do |format|
      if @fitting.save
        format.html { redirect_to @fitting, notice: 'Fitting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fitting }
      else
        format.html { render action: 'new' }
        format.json { render json: @fitting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fittings/1
  # PATCH/PUT /fittings/1.json
  def update
    respond_to do |format|
      if @fitting.update(fitting_params)
        format.html { redirect_to @fitting, notice: 'Fitting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fitting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fittings/1
  # DELETE /fittings/1.json
  def destroy
    @fitting.destroy
    respond_to do |format|
      format.html { redirect_to fittings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fitting
      @fitting = Fitting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fitting_params
      params.require(:fitting).permit(:adapter, :adapter_sticker, :data_line, :headphone, :tf_card, :holster, :remark)
    end
end

app/helpers/fittings_helper.rb
module FittingsHelper
end

app/views/fittings/_form.html.erb
<%= form_for(@fitting) do |f| %>
  <% if @fitting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fitting.errors.count, "error") %> prohibited this fitting from being saved:</h2>

      <ul>
      <% @fitting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adapter %><br>
    <%= f.text_field :adapter %>
  </div>
  <div class="field">
    <%= f.label :adapter_sticker %><br>
    <%= f.text_field :adapter_sticker %>
  </div>
  <div class="field">
    <%= f.label :data_line %><br>
    <%= f.text_field :data_line %>
  </div>
  <div class="field">
    <%= f.label :headphone %><br>
    <%= f.text_field :headphone %>
  </div>
  <div class="field">
    <%= f.label :tf_card %><br>
    <%= f.text_field :tf_card %>
  </div>
  <div class="field">
    <%= f.label :holster %><br>
    <%= f.text_field :holster %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fittings/edit.html.erb
<h1>Editing fitting</h1>

<%= render 'form' %>

<%= link_to 'Show', @fitting %> |
<%= link_to 'Back', fittings_path %>

app/views/fittings/index.html.erb
<h1>Listing fittings</h1>

<table>
  <thead>
    <tr>
      <th>Adapter</th>
      <th>Adapter sticker</th>
      <th>Data line</th>
      <th>Headphone</th>
      <th>Tf card</th>
      <th>Holster</th>
      <th>Remark</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fittings.each do |fitting| %>
      <tr>
        <td><%= fitting.adapter %></td>
        <td><%= fitting.adapter_sticker %></td>
        <td><%= fitting.data_line %></td>
        <td><%= fitting.headphone %></td>
        <td><%= fitting.tf_card %></td>
        <td><%= fitting.holster %></td>
        <td><%= fitting.remark %></td>
        <td><%= link_to 'Show', fitting %></td>
        <td><%= link_to 'Edit', edit_fitting_path(fitting) %></td>
        <td><%= link_to 'Destroy', fitting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fitting', new_fitting_path %>

app/views/fittings/new.html.erb
<h1>New fitting</h1>

<%= render 'form' %>

<%= link_to 'Back', fittings_path %>

app/views/fittings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adapter:</strong>
  <%= @fitting.adapter %>
</p>

<p>
  <strong>Adapter sticker:</strong>
  <%= @fitting.adapter_sticker %>
</p>

<p>
  <strong>Data line:</strong>
  <%= @fitting.data_line %>
</p>

<p>
  <strong>Headphone:</strong>
  <%= @fitting.headphone %>
</p>

<p>
  <strong>Tf card:</strong>
  <%= @fitting.tf_card %>
</p>

<p>
  <strong>Holster:</strong>
  <%= @fitting.holster %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @fitting.remark %>
</p>

<%= link_to 'Edit', edit_fitting_path(@fitting) %> |
<%= link_to 'Back', fittings_path %>