config/routes.rb
OnyxProductionManagement::Application.routes.draw do
  resources :bom_materiales

  resources :boms do
    member do
      get "add_materiale_to_bom"
      get "materiales_list"
      get "remove_materiale_from_materiales_list"
    end
    collection do
      get "remove_materiale_from_bom"
    end
  end

  get "import_data/import_data_view" => "import_data#import_data_view"
  post "import_data/upload"
  
  resources :manufactures do
    collection do
      post "search", to: 'manufactures#search_manufactures'
    end
  end

  resources :custom_tables do
    collection do
      get "edit_column"
      post "update_column"
    end
  end

  devise_for :users
  
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
    get    "/users/sign_in" => "devise/sessions#new"
    get    "/users/sign_up" => "devise/registrations#new"
  end
  
  resources :fittings

  resources :packaging_materials

  resources :assembly_boms

  resources :bom_events

  resources :orders

  resources :products do
    member do
      get "boms"
      get "orders"
      get "assembly_boms"
    end
  end

  resources :hardwares

  resources :softwares

  resources :assemblies

  resources :packaging_requirements

  resources :register_orders

  resources :events

  resources :types

  resources :materiales_events

  resources :materiales do    
    collection do
      post "search", to: 'materiales#search_materiales'
      post "update_materiale"
    end
  end

  root 'materiales#index'

  

end

app/models/bom.rb
class Bom
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :bom_id, type: String
  field :version, type: String
  field :state, type: String
  
  belongs_to :product
  has_many :bom_materiales, :dependent => :destroy
end

app/controllers/boms_controller.rb
class BomsController < ApplicationController
  before_action :set_bom, only: [:show, :edit, :update, :destroy, :materiales_list, :add_materiale_to_bom, :remove_materiale_from_materiales_list]

  # GET /boms
  # GET /boms.json
  def index
    @boms = Bom.all
  end

  # GET /boms/1
  # GET /boms/1.json
  def show
  end

  # GET /boms/new
  def new
    @bom = Bom.new
  end

  # GET /boms/1/edit
  def edit
  end

  # POST /boms
  # POST /boms.json
  def create
    @bom = Bom.new(bom_params)
    @bom.product_id = bom_params["product_id"]
    respond_to do |format|
      if @bom.save
        format.html { redirect_to @bom, notice: 'Bom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bom }
      else
        format.html { render action: 'new' }
        format.json { render json: @bom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boms/1
  # PATCH/PUT /boms/1.json
  def update
    respond_to do |format|
      if @bom.update(bom_params)
        format.html { redirect_to @bom, notice: 'Bom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boms/1
  # DELETE /boms/1.json
  def destroy
    @bom.destroy
    respond_to do |format|
      format.html { redirect_to boms_url }
      format.json { head :no_content }
    end
  end
  
  def materiales_list
    @materiales = Materiale.all
    respond_to do |format|
      format.html {render action: "materiales_list"}
    end
  end
  
  def add_materiale_to_bom
    @materiale = Materiale.find(params[:materiale_id])
    @bom_materiale = BomMateriale.new
    @materiale.bom_materiales << @bom_materiale
    @bom.bom_materiales << @bom_materiale
    @materiale.add_bom(@bom)
    respond_to do |format|
      format.js {@materiale}
    end
  end
  
  def remove_materiale_from_materiales_list
    @materiale = Materiale.find(params[:materiale_id])
    @bom.bom_materiales.find_by(:materiale_id => params[:materiale_id]).destroy
    @materiale.remove_bom(@bom)
    respond_to do |format|
      format.js {@materiale}
    end
  end
  
  def remove_materiale_from_bom
      @bom_materiale = BomMateriale.find(params[:bom_materiale_id])
      @bom_materiale.materiale.remove_bom(@bom_materiale.bom)
      @bom_materiale.destroy
      respond_to do |format|
      format.js {@bom_materiale}
    end   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bom
      @bom = Bom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bom_params
      params.require(:bom).permit(:bom_id, :version, :state, :product_id, :materiale_id)
    end
end

app/helpers/boms_helper.rb
module BomsHelper
end

app/views/boms/_bom.html.erb
<tr>
    <td><%= bom.bom_id %></td>
    <td><%= bom.product.name %></td>
    <td><%= bom.version %></td>
    <td><%= bom.state %></td>
    <td><%= link_to '详细', bom, :class => "btn btn-default btn-xs" %>
    <%= link_to '编辑', edit_bom_path(bom), :class => "btn btn-default btn-xs" %>
    <%= link_to '变更', boms_path, :class => "btn btn-default btn-xs" %>
    <%= link_to '删除', bom, :class => "btn btn-default btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/boms/_form.html.erb
<%= form_for(@bom) do |f| %>
  <% if @bom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bom.errors.count, "error") %> prohibited this bom from being saved:</h2>

      <ul>
      <% @bom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :bom_id %><br>
    <%= f.text_field :bom_id, :class => "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label "型号" %>
      <%= f.select :product_id, options_for_select(Product.all.collect{ |p| [p.name, p.id] }, :selected => f.object.product_id), {:include_blank => true}, {:class =>  "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :version %><br>
    <%= f.text_field :version, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/boms/_materiales_list_item.html.erb
<tr id= "<%= dom_id materiale%>">
    <td><%= materiale.onyx_p_n %></td>
    <td><%= materiale.type %></td>
    <td><%= materiale.description %></td>
    <td><%= materiale.p_n %></td>
    <td><%= materiale.substitute_code %></td>
    <td><%= materiale.substitute_p_n %></td>
    <td><%= materiale.footprint %></td>
    <td><%= materiale.mark %></td>
    <td><%= materiale.level %></td>
    <td><%= materiale.remark %></td>
    <td><%= materiale.materiale_manufacture_ships[0].manufacture.name if materiale.materiale_manufacture_ships.size > 0 %></td>
    <% if materiale.belongs_the_bom?(@bom) %>
    <td class="control-td"> <%= button_to "删除", remove_materiale_from_materiales_list_bom_path(@bom, :materiale_id => materiale.id), :method => :get, :remote => true, :class => "btn btn-danger btn-xs" %> </td>
    <% else %>
    <td class="control-td"> <%= button_to "添加", add_materiale_to_bom_bom_path(@bom, :materiale_id => materiale.id), :method => :get, :remote => true, :class => "btn btn-success btn-xs" %> </td>
    <% end %>
</tr>

app/views/boms/add_materiale_to_bom.js.erb
$("#<%= dom_id(@materiale) %>").replaceWith("<%= escape_javascript(render :partial => "materiales_list_item", locals: {materiale: @materiale}) %>");

app/views/boms/edit.html.erb
<div class="container">

    <h1>编辑Bom</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @bom %> |
    <%= link_to 'Back', boms_path %>
</div>

app/views/boms/index.html.erb
<div class="container">
    <h1>Bom列表</h1>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>型号</th>
                <th>版本</th>
                <th>状态</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <%= render @boms%>
        </tbody>
    </table>

    <br>

    <%= link_to 'New Bom', new_bom_path %>

</div>

app/views/boms/materiales_list.html.erb
<div class="well">
    <h3>添加Bom料</h3>
    <%= link_to '返回', @bom, :class => "btn btn-default btn-xs pull-right" %>
    
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>文石编码</th>
                <th>类型</th>
                <th>描述</th>
                <th>料号</th>
                <th>替代料号</th>
                <th>替代料编码</th>
                <th>封装</th>
                <th>丝印</th>
                <th>物料级别</th>
                <th>备注</th>
                <th>供应商</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <%= render :partial => "materiales_list_item", :collection => @materiales, :as => :materiale %>
        </tbody>
    </table>

</div>

app/views/boms/new.html.erb
<div class="container">
    <h1>新建Bom</h1>

    <%= render 'form' %>

    <%= link_to 'Back', boms_path %>
</div>

app/views/boms/remove_materiale_from_bom.js.erb
$("#<%= dom_id(@bom_materiale) %>").remove();

app/views/boms/remove_materiale_from_materiales_list.js.erb
$("#<%= dom_id(@materiale) %>").replaceWith("<%= escape_javascript(render :partial => "materiales_list_item", locals: {materiale: @materiale}) %>");

app/views/boms/show.html.erb
<div class="well">
    <div class="bom-info">
        <strong>Bom:</strong>
        <%= @bom.bom_id %>&nbsp;
        <strong>型号:</strong>
        <%= @bom.product.name %>
        &nbsp;
        <strong>Version:</strong>
        <%= @bom.version %>
        &nbsp;
        <strong>State:</strong>
        <%= @bom.state %>
        &nbsp;
        <%= link_to '编辑', edit_bom_path(@bom), :class => "btn btn-default btn-xs" %>
        <%= link_to '返回', boms_path, :class => "btn btn-default btn-xs" %>
        <%= link_to "添加bom料", materiales_list_bom_path(@bom), :class => "btn btn-default btn-xs" %>
    </div>
    <div class="bom-materiales-list">
        <h1>Bom料列表</h1>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>文石编码</th>
                    <th>类型</th>
                    <th>描述</th>
                    <th>料号</th>
                    <th>替代料号</th>
                    <th>替代料编码</th>
                    <th>封装</th>
                    <th>丝印</th>
                    <th>物料级别</th>
                    <th>备注</th>
                    <th>供应商</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <% @bom.bom_materiales.each do |bom_materiale| %>
                <tr id= "<%= dom_id bom_materiale%>">
                    <td><%= bom_materiale.materiale.onyx_p_n %></td>
                    <td><%= bom_materiale.materiale.type %></td>
                    <td><%= bom_materiale.materiale.description %></td>
                    <td><%= bom_materiale.materiale.p_n %></td>
                    <td><%= bom_materiale.materiale.substitute_code %></td>
                    <td><%= bom_materiale.materiale.substitute_p_n %></td>
                    <td><%= bom_materiale.materiale.footprint %></td>
                    <td><%= bom_materiale.materiale.mark %></td>
                    <td><%= bom_materiale.materiale.level %></td>
                    <td><%= bom_materiale.materiale.remark %></td>
                    <td><%= bom_materiale.materiale.manufacture %></td>
                    <td><%= button_to "修改", boms_path, :class => "btn btn-default btn-xs" %>
                        <%= button_to "删除", remove_materiale_from_bom_boms_path(:bom_materiale_id => bom_materiale), :method => :get, :remote => true, :class => "btn btn-danger btn-xs", data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
            </tbody>
            <% end %>
        </table>
    </div>
</div>