config/routes.rb
OnyxProductionManagement::Application.routes.draw do
  resources :bom_materiales

  resources :boms do
    member do
      get "add_materiale_to_bom"
      get "materiales_list"
      get "remove_materiale_from_materiales_list"
    end
    collection do
      get "remove_materiale_from_bom"
    end
  end

  get "import_data/import_data_view" => "import_data#import_data_view"
  post "import_data/upload"
  
  resources :manufactures do
    collection do
      post "search", to: 'manufactures#search_manufactures'
    end
  end

  resources :custom_tables do
    collection do
      get "edit_column"
      post "update_column"
    end
  end

  devise_for :users
  
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
    get    "/users/sign_in" => "devise/sessions#new"
    get    "/users/sign_up" => "devise/registrations#new"
  end
  
  resources :fittings

  resources :packaging_materials

  resources :assembly_boms

  resources :bom_events

  resources :orders

  resources :products do
    member do
      get "boms"
      get "orders"
      get "assembly_boms"
    end
  end

  resources :hardwares

  resources :softwares

  resources :assemblies

  resources :packaging_requirements

  resources :register_orders

  resources :events

  resources :types

  resources :materiales_events

  resources :materiales do    
    collection do
      post "search", to: 'materiales#search_materiales'
      post "update_materiale"
    end
  end

  root 'materiales#index'

  

end

app/controllers/custom_tables_controller.rb
class CustomTablesController < ApplicationController
  before_action :set_custom_table, only: [:show, :edit, :update, :destroy]

  # GET /custom_tables
  # GET /custom_tables.json
  def index
    @custom_tables = CustomTable.all
  end

  # GET /custom_tables/1
  # GET /custom_tables/1.json
  def show
  end

  # GET /custom_tables/new
  def new
    @custom_table = CustomTable.new
  end

  # GET /custom_tables/1/edit
  def edit
  end

  # POST /custom_tables
  # POST /custom_tables.json
  def create
    @custom_table = CustomTable.new(custom_table_params)

    respond_to do |format|
      if @custom_table.save
        format.html { redirect_to @custom_table, notice: 'Custom table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @custom_table }
      else
        format.html { render action: 'new' }
        format.json { render json: @custom_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_tables/1
  # PATCH/PUT /custom_tables/1.json
  def update
    respond_to do |format|
      if @custom_table.update(custom_table_params)
        format.html { redirect_to @custom_table, notice: 'Custom table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @custom_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_tables/1
  # DELETE /custom_tables/1.json
  def destroy
    @custom_table.destroy
    respond_to do |format|
      format.html { redirect_to custom_tables_url }
      format.json { head :no_content }
    end
  end
  
  def edit_column
    @table = params[:table_name]
    @columns = @table.constantize::TABLE_MAP
    user = current_user
    if !user.custom_table?
      @custom_table = CustomTable.new
      @custom_table.name = @table
      @custom_table.column = ""
      user.custom_table << @custom_table
    end
    respond_to do |format|
      format.html {render 'edit_table'}
    end
  end
  
  def update_column
    user = current_user
    @name = params[:table_name]
    @columns = params[:table_columns]
    if user.custom_table?
      @custom_table = user.custom_table.find_by(:name => @name)
      if !@custom_table    
        @custom_table = CustomTable.new
        @custom_table.name = @name
      end
    else
      @custom_table = CustomTable.new
      @custom_table.name = @name
    end
    @custom_table.column = @columns
    user.custom_table << @custom_table    
    respond_to do |format|
      format.html {redirect_to materiales_url}
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_table
      @custom_table = CustomTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_table_params
      params[:custom_table]
    end
end

app/helpers/custom_tables_helper.rb
module CustomTablesHelper
  def column_is_select(table)
    columns = []
    tables = current_user.custom_table.where(:name => table)
    tables.each do |t|
      columns = columns | t.column.split(/,/)
    end
    columns
  end
end

app/views/custom_tables/_form.html.erb
<%= form_for(@custom_table) do |f| %>
  <% if @custom_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_table.errors.count, "error") %> prohibited this custom_table from being saved:</h2>

      <ul>
      <% @custom_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_tables/edit.html.erb
<%= form_tag(edit_custom_table_path, :html => {:class => ""}) do %>
    <h2 class="form-sign-heading">设置隐藏列</h2>
    <%= Materiale::TABLE_MAP.each do |k, v| %>
    <p><%= k %><%= v %></p>
    <% end %>
        
    <div class="submit-button"><%= submit_tag "保存", :class => "btn btn-lg btn-primary btn-block" %></div>
<% end %>

app/views/custom_tables/edit_table.html.erb
<div id="edit_table_columns" class="form-edit">
    <h2 class="form-sign-heading">设置隐藏列</h2>
    <% columns = column_is_select(@table) %>
    <% @columns.each do |k, v| %>
        <% if columns.include?(k.to_s)%>
            <div class="checkbox">
                <%= check_box_tag k, k, true %>
                <%= label_tag v %>
            </div>
        <% else %>
            <div class="checkbox">
                <%= check_box_tag k, k %>
                <%= label_tag v %>
            </div>
        <% end %>
    <% end %>
    <%= form_tag(update_column_custom_tables_path, :html => {:class => ""}) do %>

        <%= hidden_field_tag 'table_name', @table%>
        <%= hidden_field_tag  'table_columns'%>
        <div class="submit-button">
            <%= submit_tag "保存", :class => "btn btn-lg btn-primary btn-block" %>
        </div>
    <% end %>
</div>

app/views/custom_tables/index.html.erb
<h1>Listing custom_tables</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_tables.each do |custom_table| %>
      <tr>
        <td><%= link_to 'Show', custom_table %></td>
        <td><%= link_to 'Edit', edit_custom_table_path(custom_table) %></td>
        <td><%= link_to 'Destroy', custom_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom table', new_custom_table_path %>

app/views/custom_tables/new.html.erb
<h1>New custom_table</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_tables_path %>

app/views/custom_tables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_custom_table_path(@custom_table) %> |
<%= link_to 'Back', custom_tables_path %>