config/routes.rb
OnyxProductionManagement::Application.routes.draw do
  resources :bom_materiales

  resources :boms do
    member do
      get "add_materiale_to_bom"
      get "materiales_list"
      get "remove_materiale_from_materiales_list"
    end
    collection do
      get "remove_materiale_from_bom"
    end
  end

  get "import_data/import_data_view" => "import_data#import_data_view"
  post "import_data/upload"
  
  resources :manufactures do
    collection do
      post "search", to: 'manufactures#search_manufactures'
    end
  end

  resources :custom_tables do
    collection do
      get "edit_column"
      post "update_column"
    end
  end

  devise_for :users
  
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
    get    "/users/sign_in" => "devise/sessions#new"
    get    "/users/sign_up" => "devise/registrations#new"
  end
  
  resources :fittings

  resources :packaging_materials

  resources :assembly_boms

  resources :bom_events

  resources :orders

  resources :products do
    member do
      get "boms"
      get "orders"
      get "assembly_boms"
    end
  end

  resources :hardwares

  resources :softwares

  resources :assemblies

  resources :packaging_requirements

  resources :register_orders

  resources :events

  resources :types

  resources :materiales_events

  resources :materiales do    
    collection do
      post "search", to: 'materiales#search_materiales'
      post "update_materiale"
    end
  end

  root 'materiales#index'

  

end

app/models/manufacture.rb
class Manufacture
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :tel, type: String
  field :remark, type: String
  field :level, type: String
  field :tags, type: Array
  
  has_many :manufacture_files, :dependent => :destroy
  has_many :materiale_manufacture_ships, :dependent => :destroy
  accepts_nested_attributes_for :manufacture_files, :allow_destroy => true
end

app/controllers/manufactures_controller.rb
class ManufacturesController < ApplicationController
  before_action :set_manufacture, only: [:show, :edit, :update, :destroy]

  # GET /manufactures
  # GET /manufactures.json
  def index
    @manufactures = Manufacture.all
  end

  # GET /manufactures/1
  # GET /manufactures/1.json
  def show
  end

  # GET /manufactures/new
  def new
    @manufacture = Manufacture.new
  end

  # GET /manufactures/1/edit
  def edit
  end

  # POST /manufactures
  # POST /manufactures.json
  def create
    @manufacture = Manufacture.new(manufacture_params)

    respond_to do |format|
      if @manufacture.save
        format.html { redirect_to @manufacture, notice: 'Manufacture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manufacture }
      else
        format.html { render action: 'new' }
        format.json { render json: @manufacture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufactures/1
  # PATCH/PUT /manufactures/1.json
  def update
    respond_to do |format|
      if @manufacture.update(manufacture_params)
        format.html { redirect_to @manufacture, notice: 'Manufacture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manufacture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufactures/1
  # DELETE /manufactures/1.json
  def destroy
    @manufacture.destroy
    respond_to do |format|
      format.html { redirect_to manufactures_url }
      format.json { head :no_content }
    end
  end
  
  def search_manufactures
    column = params[:search_category]
    keyword = params[:search_params]
    @manufactures = Manufacture.where(column => /#{keyword}/i).all
    respond_to do |format|
      format.html { render action: "index" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacture
      @manufacture = Manufacture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacture_params
      params.require(:manufacture).permit(:name, :address, :tel, :level, :tags, :remark, :manufacture_files_attributes => [:id, :type, :manufacture_file, :_destroy])
    end
end

app/helpers/manufactures_helper.rb
module ManufacturesHelper
end

app/views/manufactures/_form.html.erb
<%= nested_form_for(@manufacture, :html=>{:multipart => true }) do |f| %>
  <% if @manufacture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufacture.errors.count, "error") %> prohibited this manufacture from being saved:</h2>

      <ul>
      <% @manufacture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name , :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tel %><br>
    <%= f.text_field :tel , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :level %><br>
    <%= f.text_field :level , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :remark %><br>
    <%= f.text_area :remark , :class => "form-control", :rows => "10", :cols => "50" %>
  </div>
  <div>
      <%= f.fields_for :manufacture_files do |manufacture_file_form| %>
      <div class="form-group">
        <%= manufacture_file_form.label :type%>
        <%= manufacture_file_form.text_field :type, :class => "form-control"%>
      </div>
      <div class="form-group">
        <%= manufacture_file_form.file_field :manufacture_file %>
        <%= link_to manufacture_file_form.object.manufacture_file_filename, manufacture_file_form.object.manufacture_file_url if manufacture_file_form.object.manufacture_file? %>
      </div>
        <%= manufacture_file_form.link_to_remove "删除" %>
      <% end %>
      <%= f.link_to_add "增加文件", :manufacture_files, :class => "text-primary" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/manufactures/edit.html.erb
<div class="container">
<h1>编辑供应商</h1>

<%= render 'form' %>

<%= link_to 'Show', @manufacture %> |
<%= link_to 'Back', manufactures_path %>
</div>

app/views/manufactures/index.html.erb
<div class="well">
    <h1>供应商列表</h1>
    <div class="tools-bar" >
    <%= link_to '添加供应商', new_manufacture_path, :class => "btn btn-default pull-right" %>
        <div class="row">
            <%= form_tag(search_manufactures_path) do%>
            <div class="col-xs-1">
                <%= select_tag( 'search_category', options_for_select({'名字' => 'name'}), {:class => 'form-control'}) %>
            </div>
            
            <div class="input-group col-xs-3">
                <%= text_field_tag :search_params, params[:search_params], :class => 'form-control' %>
                <span class="input-group-btn">
                    <%= submit_tag "搜索", :class => "btn btn-default", :id => "search_button" %>
                </span>
            </div>
        <%end%>
        </div>
    </div>

    <div class="row">
        <% @manufactures.each do |manufacture| %>
        <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
                <h4><%= manufacture.name %></h4>
                <p>
                    地址：<%= manufacture.address %>
                </p>
                <p>
                    电话：<%= manufacture.tel %>
                </p>
                <p>
                    Level：<%= manufacture.level %>
                </p>
                <p>
                    备注：<%= manufacture.remark %>
                </p>
                <div>
                    <%= link_to '详细', manufacture, :method => :get, :class => "btn btn-default btn-xs " %>
                    <%= link_to '编辑', edit_manufacture_path(manufacture), :method => :get, :class => "btn btn-default btn-xs" %>
                    <%= link_to '删除', manufacture, method: :delete, :class => "btn btn-default btn-xs", data: { confirm: 'Are you sure?' }%>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/manufactures/new.html.erb
<div class="container">
<h1>添加供应商</h1>

<%= render 'form' %>

<%= link_to 'Back', manufactures_path %>
</div>

app/views/manufactures/show.html.erb
<div class="container">
<div class="well">
    <p>
        <strong>Name:</strong>
        <%= @manufacture.name %>
    </p>

    <p>
        <strong>Address:</strong>
        <%= @manufacture.address %>
    </p>

    <p>
        <strong>Tel:</strong>
        <%= @manufacture.tel %>
    </p>

    <p>
        <strong>Level:</strong>
        <%= @manufacture.level %>
    </p>

    <p>
        <strong>Remark:</strong><br />
        <%= @manufacture.remark %>
    </p>
    <p>
        <strong>Document:</strong> <br />
        <% @manufacture.manufacture_files.each do |file| %>
            <%= link_to file.manufacture_file_filename, file.manufacture_file_url %><br />
        <% end %>
    </p>

    <%= link_to 'Edit', edit_manufacture_path(@manufacture), :class => "btn btn-default" %> |
    <%= link_to 'Back', manufactures_path, :class => "btn btn-default" %>
</div>
</div>